[Media API]: Requesting API Review
MicrosoftEdge/WebView2Feedback pull request #1658
Opened 2021-08-18 13:06 UTC by dianaqu

2021-08-24 18:38 UTC, david-risney requested changes

2021-08-24 18:38 UTC, david-risney commented on specs/Media.md
> +interface ICoreWebView2_2 : ICoreWebView2 {
This should probably be a bigger number
```suggestion
interface ICoreWebView2_6 : ICoreWebView2 {
```

2021-08-24 18:38 UTC, david-risney commented on specs/Media.md
> +interface ICoreWebView2StagingIsAudioPlayingChangedEventHandler : IUnknown {
Please use approximate final names - remove staging from here and also from above in the sample code

```suggestion
interface ICoreWebView2IsAudioPlayingChangedEventHandler : IUnknown {
```

2021-08-30 06:36 UTC, dianaqu commented on specs/Media.md
> +    CHECK_FAILURE(m_webView->Mute());
Updated

2021-08-30 06:36 UTC, dianaqu commented on specs/Media.md
> +interface ICoreWebView2_6 : ICoreWebView2 {
Updated

2021-09-13 14:30 UTC, dianaqu commented on specs/Media.md
> +            void Mute();
Making it settable. End developer doesn't seem to have a preference and I update the sample code

2021-09-13 16:59 UTC, Symbai commented
It would be nice if the developer gets the source of the media which requested audio. For example if a developer wants to allow media of a specific source but disallow media from everywhere else, its kinda hard/impossible to achieve this with this API.

2021-09-14 10:43 UTC, dianaqu commented
> It would be nice if the developer gets the source of the media which requested audio. For example if a developer wants to allow media of a specific source but disallow media from everywhere else, its kinda hard/impossible to achieve this with this API.

Would you mind elaborate on what you mean? This current spec is only to get/set the mute state or get the audible state. We don't hold on any sources

2021-09-14 11:42 UTC, Symbai commented
> 
> Would you mind elaborate on what you mean? This current spec is only to get/set the mute state or get the audible state. We don't hold on any sources

I want to (un)mute audio when it comes from a specific URL (the media, not the website), rather than mute/unmute whole tab. Unless that is not possible in Edge itself? In this case nevermind please.

2021-09-14 15:30 UTC, oldnewthing commented
> I want to (un)mute audio when it comes from a specific URL (the media, not the website), rather than mute/unmute whole tab. Unless that is not possible in Edge itself? In this case nevermind please.

This API does not provide that degree of control. This API controls muting at the WebView level.

It gets complicated if there is more than one media element on the page, or if that media element has multiple sources. I guess you can inject script into the page that hunts down all `<video>` elements and then studies each one to decide whether to mute it. (And use a MutationObserver to learn when new `<video>` elements are added.)

2021-09-15 17:15 UTC, merged