NavigationCompletedEventArgs.StatusCode API draft
MicrosoftEdge/WebView2Feedback pull request #2230
Opened 2022-02-28 19:55 UTC by quietfanatic

This is a draft for the API spec for the StatusCode property of NavigationCompletedEventArgs.

2022-03-01 18:17 UTC, david-risney requested changes

2022-03-01 18:17 UTC, david-risney commented on specs/StatusCode.md
> +    [propget] HRESULT StatusCode([out, retval] int* status_code);
Let's do INT instead of int. I know we use int for some cases including StatusCode elsewhere but the norm for IDL is INT not int.

2022-03-01 18:32 UTC, quietfanatic commented on specs/StatusCode.md
> +                ICoreWebView2NavigationCompletedEventArgs2* args2;
Unfortunately wil::com_ptr is not quite that convenient.  This still requires a QI or casting the right side to a wil::com_ptr (less efficient).

2022-03-01 18:33 UTC, quietfanatic commented on specs/StatusCode.md
> +    [propget] HRESULT StatusCode([out, retval] int* status_code);
Oh I figured if it overlapped with the description, there was no need to include it here.  I'll put it here too.

2022-03-01 18:39 UTC, quietfanatic commented on specs/StatusCode.md
> +            int StatusCode { get; };
Yes, it's standard practice to use an int for status codes.  I'm pretty sure the browser will reject a response with a status code larger than 999 (maybe even larger than 599).  Smaller integer types are only useful to reduce packed storage; they aren't any more efficient to pass around (and are sometimes less efficient).

2022-03-03 20:12 UTC, david-risney commented on specs/StatusCode.md
> +    ///   the hostname was not found, or if there was a network error.
(Just FYI your documentation for StatusCode is excellent 👍. Love covering the edge cases with why and actual examples)

2022-03-03 20:13 UTC, david-risney approved these changes
Looks good! Please complete this PR and open a new PR to main and let me know when its ready and I will schedule a review. Thx

2022-03-03 21:33 UTC, merged