Add spec for WebResourceRequested.md
MicrosoftEdge/WebView2Feedback pull request #454
Opened 2020-09-19 02:22 UTC by champnic

This is a review for the new WebResourceRequested API.

2020-09-19 02:34 UTC, champnic commented
Testing general discussion comment.

2020-09-19 02:35 UTC, champnic commented on specs/WebResourceRequested.md
> +    and the following quote banner:
Comment about this line. Must change.

2020-09-24 18:45 UTC, david-risney commented
Was this a test PR? Is it OK to close it or rename it so I don't accidentally go to review it in my list =) ?

2020-09-24 18:49 UTC, david-risney requested changes
Just the one question if this is intended to be a test PR and if so can we close it or rename it away from "Add spec for WebResourceRequested" so I don't click on it in my PR list.

2020-09-24 19:33 UTC, closed without merging

2020-09-24 19:33 UTC, champnic commented
Ha, forgot about this. Thanks for reminding me :)